---
.catalog:
  name: Bivac
  version: '1.1.0'
  description: "Bivac : Backup Interface for Volumes Attached to Containers"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: BIVAC_IMAGE_REPOSITORY
      label: Image repository
      description: The image repository to use.
      type: string
      default: camptocamp/bivac
      required: true
    - variable: BIVAC_IMAGE_TAG
      label: Image tag
      description: The image tag to use.
      type: string
      default: latest
      required: true
    - variable: BIVAC_RUN_TIME
      label: Schedule run time
      description: The cron schedule for the job.
      type: string
      default: 0 2 * * *
      required: true
    - variable: BIVAC_FULL_IF_OLDER_THAN
      label: Full if older than
      description: Perform a full backup if the latest full backup in the collection is older than the given time.
      type: string
      default: 15D
      required: false
    - variable: BIVAC_REMOVE_OLDER_THAN
      label: Remove older than
      description: Delete all backup sets older than the given time.
      type: string
      default: 30D
      required: false
    - variable: BIVAC_VOLUMES_BLACKLIST
      label: Volumes blacklist
      description: Comma separated list of named volumes to blacklist.
      type: string
      default: rancher-agent-state,rancher-cni-driver
      required: false
    - variable: BIVAC_VOLUMES_WHITELIST
      label: Volumes whitelist
      description: Comma separated list of named volumes to whitelist.
      type: string
      required: false
    - variable: BIVAC_NO_VERIFY
      label: No verify
      description: Whether to skip verification of volume backups.
      type: boolean
      required: false
      default: false
    - variable: BIVAC_TARGET_URL
      label: Target URL
      description: Target URL passed to backup engine. The hostname and the name of the volume to backup are added to the path as directory levels.
      type: string
      required: true
    - variable: BIVAC_ENGINE
      label: Bivac engine
      description: The engine that Bivac should use to make a backup.
      type: string
      required: false
      default: restic
    - variable: PUSHGATEWAY_URL
      label: Prometheus Pushgateway URL
      description: Prometheus Pushgateway service to push metrics to.
      type: string
      default: http://pushgateway.metrics:9091
      required: true
    - variable: RESTIC_PASSWORD
      label: Restic Password
      description: Restic Password
      type: password
      required: true
    - variable: AWS_ACCESS_KEY_ID
      label: AWS_ACCESS_KEY_ID
      description: AWS_ACCESS_KEY_ID
      type: string
      required: false
    - variable: AWS_SECRET_ACCESS_KEY
      label: AWS_SECRET_ACCESS_KEY
      description: AWS_SECRET_ACCESS_KEY
      type: password
      required: false
    - variable: OS_AUTH_URL
      label: OS_AUTH_URL
      description: OS_AUTH_URL
      type: string
    - variable: OS_TENANT_NAME
      label: OS_TENANT_NAME
      description: OS_TENANT_NAME
      type: string
    - variable: OS_USERNAME
      label: OS_USERNAME
      description: OS_USERNAME
      type: string
    - variable: OS_PASSWORD
      label: OS_PASSWORD
      description: OS_PASSWORD
      type: password
    - variable: OS_REGION_NAME
      label: OS_REGION_NAME
      description: OS_REGION_NAME
      type: string
    - variable: OS_USER_DOMAIN_NAME
      label: OS_USER_DOMAIN_NAME
      description: OS_USER_DOMAIN_NAME
      type: string
    - variable: OS_PROJECT_NAME
      label: OS_PROJECT_NAME
      description: OS_PROJECT_NAME
      type: string
    - variable: OS_PROJECT_DOMAIN_NAME
      label: OS_PROJECT_DOMAIN_NAME
      description: OS_PROJECT_DOMAIN_NAME
      type: string
    - variable: JSON_OUTPUT
      label: JSON Output
      description: Output logs as JSON
      type: boolean
      default: false
    - variable: BIVAC_LOG_LEVEL
      label: Log level
      description: Log level
      type: enum
      options:
        - debug
        - info
        - warn
        - error
        - fatal
        - panic
      default: info
