---
.catalog:
  name: Bivac
  version: '2.0.0'
  description: "Bivac : Backup Interface for Volumes Attached to Containers"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: BIVAC_IMAGE_REPOSITORY
      label: Image repository
      description: The image repository to use.
      type: string
      default: camptocamp/bivac
      required: true
    - variable: BIVAC_IMAGE_TAG
      label: Image tag
      description: The image tag to use.
      type: string
      default: 2.1
      required: true
    - variable: BIVAC_VOLUMES_BLACKLIST
      label: Volumes blacklist
      description: Comma separated list of named volumes to blacklist.
      type: string
      default: rancher-agent-state,rancher-cni-driver
      required: false
    - variable: BIVAC_VOLUMES_WHITELIST
      label: Volumes whitelist
      description: Comma separated list of named volumes to whitelist.
      type: string
      required: false
    - variable: BIVAC_TARGET_URL
      label: Target URL
      description: Target URL passed to backup engine. The hostname and the name of the volume to backup are added to the path as directory levels.
      type: string
      required: true
    - variable: BIVAC_VERBOSE
      label: Verbose
      description: Enable verbose mode.
      type: string
      default: "false"
      required: false
    - variable: BIVAC_SERVER_PSK
      label: Server's PSK
      description: Bivac instance's pre-shared key
      type: password
      required: true
    - variable: BIVAC_LOG_SERVER
      label: Bivac logging server
      description: Address of a Bivac log receiver.
      type: string
      required: false
    - variable: BIVAC_AGENT_IMAGE
      label: Agent's Docker image
      label: Docker image the Bivac agents should use.
      type: string
      required: true
      default: camptocamp/bivac:2.1
    - variable: RESTIC_PASSWORD
      label: Restic Password
      description: Restic Password
      type: password
      required: true
    - variable: AWS_ACCESS_KEY_ID
      label: AWS_ACCESS_KEY_ID
      description: AWS_ACCESS_KEY_ID
      type: string
      required: false
    - variable: AWS_SECRET_ACCESS_KEY
      label: AWS_SECRET_ACCESS_KEY
      description: AWS_SECRET_ACCESS_KEY
      type: password
      required: false
    - variable: OS_AUTH_URL
      label: OS_AUTH_URL
      description: OS_AUTH_URL
      type: string
    - variable: OS_TENANT_NAME
      label: OS_TENANT_NAME
      description: OS_TENANT_NAME
      type: string
    - variable: OS_USERNAME
      label: OS_USERNAME
      description: OS_USERNAME
      type: string
    - variable: OS_PASSWORD
      label: OS_PASSWORD
      description: OS_PASSWORD
      type: password
    - variable: OS_REGION_NAME
      label: OS_REGION_NAME
      description: OS_REGION_NAME
      type: string
    - variable: OS_USER_DOMAIN_NAME
      label: OS_USER_DOMAIN_NAME
      description: OS_USER_DOMAIN_NAME
      type: string
    - variable: OS_PROJECT_NAME
      label: OS_PROJECT_NAME
      description: OS_PROJECT_NAME
      type: string
    - variable: OS_PROJECT_DOMAIN_NAME
      label: OS_PROJECT_DOMAIN_NAME
      description: OS_PROJECT_DOMAIN_NAME
      type: string
