version: '2'
.catalog:
  name: "metrics"
  version: "v37"
  description: "Camptocamp Prometheus-based monitoring system. Add mandatory 'monitoring=true' label on exactly one host before installing."
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "SSL_CERTIFICATE"
      label: "SSL Certificate"
      description: "A valid certificate from Rancher's infrastructure. Consider using Letsencrypt from the community catalog if you don't have any. The CN must match the 'Prometheus FQDN' below."
      type: "string"
      required: true
    - variable: "PROMETHEUS_USERNAME"
      label: "Prometheus username"
      description: "Credentials used to access the prometheus API endpoint over HTTP."
      type: "string"
      required: true
    - variable: "PROMETHEUS_PASSWORD"
      label: "Prometheus password"
      description: "See Prometheus username"
      type: "password"
      required: true
    - variable: "PROMETHEUS_FQDN"
      label: "Prometheus FQDN. Must match the CN from the 'SSL Certificate' above."
      description: "The public FQDN (or IP address) where prometheus can be reached. Leave blank if you don't want this instance to be part of the central federation system."
      type: "string"
      required: false
    - variable: "PROMETHEUS_PORT"
      label: "Prometheus port"
      description: "The port used to access prometheus."
      type: "string"
      default: "9443"
      required: true
    - variable: "PROMETHEUS_SCHEME"
      label: "Prometheus scheme"
      description: "Don't change the default unless you know what you're doing."
      type: "enum"
      options:
        - "https"
        - "http"
      default: "https"
    - variable: "GRAFANA_URL"
      label: "Grafana URL"
      description: "URL of Grafana instance, which will be added to outgoing CORS headers."
      type: "string"
      default: "https://grafana.camptocamp.com"
      required: true

services:
  statsd:
    scale: 1
    retain_ip: true
  pushgateway:
    scale: 1
    retain_ip: true
  rancher:
    scale: 1
  prometheus-server:
    scale: 1
  prometheus:
    scale: 1
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
      strategy: recreate
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        global
            log 10.42.24.10:514 local2

        defaults
            log       global
            mode      http
            option    httplog
            log-tag   haproxy-promssl

        listen stats
            bind *:8008
            stats enable
            stats uri /stats

        userlist prometheus
            group prometheus
            user ${PROMETHEUS_USERNAME} insecure-password ${PROMETHEUS_PASSWORD} groups prometheus

        backend 9443_
            acl valid_user http_auth(prometheus)
            http-request auth realm Prometheus if !valid_user
            http-request deny if METH_POST { path_beg /-/ }
            acl is_delete method DELETE #Pre-defined ACL METH_DELETE does not exist in haproxy 1.6
            http-request deny if is_delete
            rspadd Access-Control-Allow-Origin:\ ${GRAFANA_URL}
            rspadd Access-Control-Allow-Credentials:\ true

      default_cert: ${SSL_CERTIFICATE}
      port_rules:
      - protocol: ${PROMETHEUS_SCHEME}
        service: prometheus-server
        source_port: ${PROMETHEUS_PORT}
        target_port: 9090
