---
version: "2"
.catalog:
  name: "Puppet"
  version: "v2.7.2-22"
  description: "Puppet Master stack"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "DNS_ALT_NAMES"
      label: "Puppetmaster dns_alt_names"
      description: "Puppet dns_alt_names to use"
      default: "puppet"
      type: "string"
      required: true
    - variable: "CA_DNS_ALT_NAMES"
      label: "Puppet CA dns_alt_names"
      description: "Puppet CA dns_alt_names to use"
      default: "puppetca"
      type: "string"
      required: true
    - variable: "DB_DNS_ALT_NAMES"
      label: "PuppetDB dns_alt_names"
      description: "PuppetDB dns_alt_names to use"
      default: "puppetdb"
      type: "string"
      required: true
    - variable: "ACTIVEMQ_DNS_ALT_NAMES"
      label: "ActiveMQ dns_alt_names"
      description: "ActiveMQ dns_alt_names to use"
      type: "string"
    - variable: "PUPPETDB_POSTGRES_SERVICE"
      label: "PuppetDB PostgreSQL"
      description: "PuppetDB PostgreSQL Service"
      type: "service"
      required: true
    - variable: "PUPPETDB_POSTGRES_USER"
      label: "PuppetDB PostgreSQL user"
      description: "PuppetDB PostgreSQL user"
      type: "string"
      default: "puppetdb"
      required: true
    - variable: "PUPPETDB_POSTGRES_PASSWORD"
      label: "PuppetDB PostgreSQL password"
      description: "PuppetDB PostgreSQL password"
      type: "password"
      default: "puppetdb"
      required: true
    - variable: "PUPPETDB_POSTGRES_RO_SUBNAME"
      label: "PuppetDB PostgreSQL read database uri"
      description: "PuppetDB PostgreSQL read database uri"
      type: "string"
      required: false
    - variable: "GITHUB_TOKEN"
      label: "GitHub token"
      description: "Token for r10k checkouts of private repositories on GitHub and MCollective keys deployment"
      type: "password"
      required: false
    - variable: "GITHUB_ORG"
      label: "GitHub Organization"
      description: "A GitHub Organization for MCollective authorization"
      type: "string"
      required: false
    - variable: "GITHUB_TEAM"
      label: "GitHub Team"
      description: "A GitHub Team for MCollective authorization"
      type: "string"
      required: false
    - variable: "GITHUB_USERS"
      label: "GitHub Users"
      description: "Additional GitHub users for MCollective services"
      type: "string"
      default: "<github_token_user>=webhook"
      required: false
    - variable: "RSA_PRIVATE_KEY"
      label: "RSA private key"
      description: "RSA private key for r10k communications"
      type: "multiline"
      required: true
    - variable: "MCOLLECTIVE_SERVER_KEY"
      label: "MCollective server key"
      description: "MCollective shared SSL server key"
      type: "multiline"
      required: true
    - variable: "GPG_KEY"
      label: "Puppetmaster GPG key to decrypt"
      description: "GPG key used by puppetmaster to decrypt hiera eyaml data"
      type: "multiline"
      required: false
    - variable: "CA_KEY"
      label: "Puppet CA private key"
      description: "Puppet CA private key"
      type: "multiline"
      required: false
    - variable: "CA_CRT"
      label: "Puppet CA certificate"
      description: "Puppet CA certificate"
      type: "multiline"
      required: false
    - variable: "WEBHOOK_SECRET"
      label: "Webhook secret"
      description: "The secret passed to the webhook"
      type: "password"
      required: true
    - variable: "PUPPET_JAVA_ARGS"
      label: "Puppetserver JAVA_ARGS"
      desription: "Puppetserver JAVA_ARGS"
      type: "string"
      default: "-XX:OnOutOfMemoryError=\"kill -9 %p\" -Djava.security.egd=/dev/urandom -Xmx2g -Xms2g -XX:MaxPermSize=256m"
      required: true
    - variable: "PUPPETDB_JAVA_ARGS"
      label: "PuppetDB JAVA_ARGS"
      desription: "PuppetDB JAVA_ARGS"
      type: "string"
      default: "-XX:OnOutOfMemoryError=\"kill -9 %p\" -Djava.security.egd=/dev/urandom -Xmx192m"
      required: true
    - variable: "PUPPETCA_JAVA_ARGS"
      label: "Puppet CA JAVA_ARGS"
      desription: "Puppet CA JAVA_ARGS"
      type: "string"
      default: "-XX:OnOutOfMemoryError=\"kill -9 %p\" -Djava.security.egd=/dev/urandom -Xmx2g -Xms2g -XX:MaxPermSize=256m"
      required: true
    - variable: "PUPPETBOARD_OVERVIEW_FILTER"
      label: "Puppetboard Overview filter"
      description: "Puppetboard Overview filter"
      type: "string"
      required: false
    - variable: "PUPPETBOARD_INVENTORY_FACTS"
      label: "Puppetboard Inventory Facts"
      description: "Facts to display in the Puppetboard Inventory"
      type: "string"
      default: "[('Hostname', 'fqdn'), ('IP Address', 'ipaddress'), ('OS', 'lsbdistdescription'), ('Architecture', 'hardwaremodel'), ('Kernel Version', 'kernelrelease'), ('Puppet Version', 'puppetversion'), ]"
      required: false
    - variable: "R10K_REMOTE"
      label: "r10k remote"
      description: "r10k remote"
      type: "string"
      required: true
    - variable: "AUTH_CONF_ALLOW_CATALOG"
      label: "auth.conf allow catalog"
      description: "Allowed certnames for catalog endpoint"
      type: "string"
      required: false
    - variable: "STOMP_PASSWORD"
      label: "MCollective's stomp password"
      description: "Password used to connect to the broker for MCollective"
      type: "password"
      required: true
    - variable: "AUTOSIGN_PSK"
      label: "Autosign PSK"
      description: "Shared secret to autosign certificates"
      type: "password"
      required: false

services:
  puppetca:
    health_check:
      port: 8140
      interval: 10000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  puppetdb:
    health_check:
      port: 8080
      interval: 10000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  activemq:
    health_check:
      port: 61613
      interval: 10000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  puppet:
    health_check:
      port: 8140
      interval: 10000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  puppetboard:
    health_check:
      port: 80
      interval: 10000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
