.catalog:
  name: "Posgresql-cluster"
  version: "v9.5-c2c3"
  description: "PostgreSQL Cluster"
  uuid: postgres-cluster-9
  minimum_rancher_version: v0.44.0
  questions:
    - variable: "POSTGRES_IMAGE"
      label: "PosgreSQL image"
      description: "PosgreSQL Docker image to use"
      type: "string"
      required: true
      default: "postgres:9.5"
    - variable: "POSTGRES_PARAMS"
      label: "PostgreSQL parameters"
      description: "PostgreSQL run-time parameters"
      type: "string"
      required: false
      default: "--log-statement=all"
    - variable: "INSTALL_POSTGIS"
      label: "Install PostGIS"
      description: "Install PostGIS and pgRouting"
      type: "boolean"
      required: true
      default: "false"
    - variable: "POSTGRES_VOLUME_NAME"
      label: "POSTGRES_VOLUME_NAME"
      description: "Volume name used to store PostgreSQL cluster"
      type: "string"
      required: true
      default: "pgdata"
    - variable: "REPLICATOR_PASSWORD"
      label: "Replicator user's password"
      description: "Password used for replication"
      type: "password"
      required: true
    - variable: "PGHOARD_STORAGE_TYPE"
      label: "PGHoard Storage type"
      description: "Storage type for PGHoard"
      type: "enum"
      options:
        - "s3"
        - "swift"
    - variable: "PGHOARD_STORAGE_TARGET"
      label: "PGHoard Storage target"
      description: "Storage target for PGHoard (s3 bucket or swift container)"
      type: "string"
      default: "pghoard"
    - variable: "AWS_ACCESS_KEY_ID"
      label: "AWS_ACCESS_KEY_ID"
      description: "AWS_ACCESS_KEY_ID"
      type: "string"
    - variable: "AWS_SECRET_ACCESS_KEY"
      label: "AWS_SECRET_ACCESS_KEY"
      description: "AWS_SECRET_ACCESS_KEY"
      type: "password"
    - variable: "AWS_DEFAULT_REGION"
      label: "AWS_DEFAULT_REGION"
      description: "AWS_DEFAULT_REGION"
      type: "string"
      default: "eu-west-1"
    - variable: "OS_USERNAME"
      label: "OS_USERNAME"
      description: "OS_USERNAME"
      type: "string"
    - variable: "OS_PASSWORD"
      label: "OS_PASSWORD"
      description: "OS_PASSWORD"
      type: "password"
    - variable: "OS_AUTH_URL"
      label: "OS_AUTH_URL"
      description: "OS_AUTH_URL"
      type: "string"
      default: "https://auth.cloud.ovh.net/v2.0"
    - variable: "OS_TENANT_NAME"
      label: "OS_TENANT_NAME"
      description: "OS_TENANT_NAME"
      type: "string"
    - variable: "OS_REGION_NAME"
      label: "OS_REGION_NAME"
      description: "OS_REGION_NAME"
      type: "string"
