---
.catalog:
  name: Bivac
  version: 1.0.1
  description: "Bivac : Backup Interface for Volumes Attached to Containers"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: BIVAC_IMAGE_REPOSITORY
      label: Image repository
      description: The image repository to use.
      type: string
      default: camptocamp/bivac
      required: true
    - variable: BIVAC_IMAGE_TAG
      label: Image tag
      description: The image tag to use.
      type: string
      default: latest
      required: true
    - variable: BIVAC_RUN_TIME
      label: Schedule run time
      description: The cron schedule for the job.
      type: string
      default: 0 2 * * *
      required: true
    - variable: BIVAC_FULL_IF_OLDER_THAN
      label: Full if older than
      description: Perform a full backup if the latest full backup in the collection is older than the given time.
      type: string
      default: 15D
      required: false
    - variable: BIVAC_REMOVE_OLDER_THAN
      label: Remove older than
      description: Delete all backup sets older than the given time.
      type: string
      default: 30D
      required: false
    - variable: BIVAC_VOLUMES_BLACKLIST
      label: Volumes blacklist
      description: Comma separated list of named volumes to blacklist.
      type: string
      required: false
    - variable: BIVAC_NO_VERIFY
      label: No verify
      description: Whether to skip verification of volume backups.
      type: boolean
      required: false
      default: false
    - variable: BIVAC_TARGET_URL
      label: Target URL
      description: Target URL passed to backup engine. The hostname and the name of the volume to backup are added to the path as directory levels.
      type: string
      required: true
    - variable: PUSHGATEWAY_URL
      label: Prometheus Pushgateway URL
      description: Prometheus Pushgateway service to push metrics to.
      type: string
      default: http://pushgateway.metrics:9091
      required: true
    - variable: AWS_ACCESS_KEY_ID
      label: AWS_ACCESS_KEY_ID
      description: AWS_ACCESS_KEY_ID
      type: string
      required: false
    - variable: AWS_SECRET_ACCESS_KEY
      label: AWS_SECRET_ACCESS_KEY
      description: AWS_SECRET_ACCESS_KEY
      type: password
      required: false
    - variable: SWIFT_AUTHURL
      label: SWIFT_AUTHURL
      description: SWIFT_AUTHURL
      type: string
    - variable: SWIFT_TENANTNAME
      label: SWIFT_TENANTNAME
      description: SWIFT_TENANTNAME
      type: string
    - variable: SWIFT_USERNAME
      label: SWIFT_USERNAME
      description: SWIFT_USERNAME
      type: string
    - variable: SWIFT_PASSWORD
      label: SWIFT_PASSWORD
      description: SWIFT_PASSWORD
      type: password
    - variable: SWIFT_REGIONNAME
      label: SWIFT_REGIONNAME
      description: SWIFT_REGIONNAME
      type: string
    - variable: JSON_OUTPUT
      label: JSON Output
      description: Output logs as JSON
      type: boolean
      default: false
    - variable: BIVAC_LOG_LEVEL
      label: Log level
      description: Log level
      type: enum
      options:
        - debug
        - info
        - warn
        - error
        - fatal
        - panic
      default: info
