name: psitransfer                                                                                                                                                                                                                                          
description: |
  Transfer service
version: v1
category: "Camptocamp services"
