version: '2'
.catalog:
  name: "Posgresql-cluster"
  version: "v43"
  description: "PostgreSQL Cluster"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "POSTGRES_IMAGE"
      label: "PosgreSQL image"
      description: "PosgreSQL Docker image to use"
      type: "enum"
      options:
        - "postgres"
        - "camptocamp/postgres"
      required: true
      default: "postgres"
    - variable: "POSTGRES_VERSION"
      label: "PostgreSQL version"
      description: "PostgreSQL version to use"
      type: "enum"
      options:
        - "9.5"
        - "9.6"
      required: true
      default: "9.6"
    - variable: "POSTGRES_PARAMS"
      label: "PostgreSQL parameters"
      description: "PostgreSQL run-time parameters"
      type: "string"
      required: false
      default: "--log-statement=all"
    - variable: "POSTGRES_VOLUME_NAME"
      label: "POSTGRES_VOLUME_NAME"
      description: "Volume name used to store PostgreSQL cluster"
      type: "string"
      required: true
      default: "pgdata"
    - variable: "POSTGRES_USER"
      label: "PostgreSQL User"
      description: "PostgreSQL User"
      type: "string"
      default: "postgres"
    - variable: "POSTGRES_PASSWORD"
      label: "PostgreSQL Password"
      description: "PostgreSQL Password"
      type: "password"
      required: true
    - variable: "REPLICATOR_PASSWORD"
      label: "Replicator user's password"
      description: "Password used for replication"
      type: "password"
      required: true
    - variable: "HOST_LABEL"
      label: "Host label"
      description: "Host label"
      type: "string"
      default: "database=true"
      required: true
    - variable: "LB_LABEL"
      label: "Load Balancer label"
      description: "Load Balancer label"
      type: "string"
      default: "database=true"
      required: true
    - variable: "PGHOARD_LABEL"
      label: "PGHoard label"
      description: "PGHoard label"
      type: "string"
      default: "database=true"
      required: true
    - variable: "PGHOARD_STORAGE_TYPE"
      label: "PGHoard Storage type"
      description: "Storage type for PGHoard"
      type: "enum"
      options:
        - "local"
        - "s3"
        - "swift"
    - variable: "PGHOARD_STORAGE_TARGET"
      label: "PGHoard Storage target"
      description: "Storage target for PGHoard (s3 bucket or swift container)"
      type: "string"
      default: "pghoard"
    - variable: "PGHOARD_ACTIVE_BACKUP_MODE"
      label: "PGHoard active backup mode"
      description: "PGHoard active backup mode"
      type: "enum"
      options:
        - "pg_receivexlog"
        - "walreceiver"
      default: "pg_receivexlog"
    - variable: "PGHOARD_BASEBACKUP_COUNT"
      label: "PGHoard basebackup count"
      description: "How many basebackups should be kept around for restoration purposes."
      type: "integer"
      default: 1
    - variable: "PGHOARD_BASEBACKUP_INTERVAL_HOURS"
      label: "PGHoard basebackup interval hours"
      description: "How often to take a new basebackup of a cluster."
      type: "integer"
      default: 24
    - variable: "AWS_ACCESS_KEY_ID"
      label: "AWS_ACCESS_KEY_ID"
      description: "AWS_ACCESS_KEY_ID"
      type: "string"
    - variable: "AWS_SECRET_ACCESS_KEY"
      label: "AWS_SECRET_ACCESS_KEY"
      description: "AWS_SECRET_ACCESS_KEY"
      type: "password"
    - variable: "AWS_DEFAULT_REGION"
      label: "AWS_DEFAULT_REGION"
      description: "AWS_DEFAULT_REGION"
      type: "string"
    - variable: "AWS_HOST"
      label: "AWS_HOST"
      description: "override host for non AWS-S3 implementations"
      type: "string"
    - variable: "OS_USERNAME"
      label: "OS_USERNAME"
      description: "OS_USERNAME"
      type: "string"
    - variable: "OS_PASSWORD"
      label: "OS_PASSWORD"
      description: "OS_PASSWORD"
      type: "password"
    - variable: "OS_AUTH_URL"
      label: "OS_AUTH_URL"
      description: "OS_AUTH_URL"
      type: "string"
    - variable: "OS_TENANT_NAME"
      label: "OS_TENANT_NAME"
      description: "OS_TENANT_NAME"
      type: "string"
    - variable: "OS_REGION_NAME"
      label: "OS_REGION_NAME"
      description: "OS_REGION_NAME"
      type: "string"
    - variable: "HAPROXY_TIMEOUT"
      label: "HAProxy timeout"
      description: "HAProxy timeout"
      type: "string"
      default: "10800s"
      required: true
    - variable: "RO_REPLICAS_ONLY"
      label: "RO replicas only"
      description: "Read-only endpoint on replicas only."
      type: "boolean"
      default: "false"
      required: true

services:
  postgres:
    metadata:
      credentials:
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
