---
.catalog:
  name: "Postgres-cluster"
  version: "v6"
  description: "PostgreSQL Incremental Backup Cluster"
  uuid: "postgres-cluster-6"
  minimum_rancher_version: "v1.0.0"
  questions:
    - variable: "POSTGRES_VOLUME_NAME"
      label: "POSTGRES_VOLUME_NAME"
      description: "Volume name used to store PostgreSQL cluster"
      type: "string"
      required: true
      default: "pgdata"
    - variable: "STORAGE_TYPE"
      label: "Storage type"
      description: "Storage type for backup"
      type: "enum"
      options:
        - "s3"
        - "swift"
    - variable: "STORAGE_TARGET"
      label: "Storage target"
      description: "Storage target for backup (s3 bucket or swift container)"
      type: "string"
      default: "pghoard"
    - variable: "AWS_ACCESS_KEY_ID"
      label: "AWS_ACCESS_KEY_ID"
      description: "AWS_ACCESS_KEY_ID"
      type: "string"
    - variable: "AWS_SECRET_ACCESS_KEY"
      label: "AWS_SECRET_ACCESS_KEY"
      description: "AWS_SECRET_ACCESS_KEY"
      type: "password"
    - variable: "AWS_DEFAULT_REGION"
      label: "AWS_DEFAULT_REGION"
      description: "AWS_DEFAULT_REGION"
      type: "string"
      default: "eu-west-1"
    - variable: "OS_USERNAME"
      label: "OS_USERNAME"
      description: "OS_USERNAME"
      type: "string"
    - variable: "OS_PASSWORD"
      label: "OS_PASSWORD"
      description: "OS_PASSWORD"
      type: "password"
    - variable: "OS_AUTH_URL"
      label: "OS_AUTH_URL"
      description: "OS_AUTH_URL"
      type: "string"
      default: "https://auth.cloud.ovh.net/v2.0"
    - variable: "OS_TENANT_NAME"
      label: "OS_TENANT_NAME"
      description: "OS_TENANT_NAME"
      type: "string"
    - variable: "OS_REGION_NAME"
      label: "OS_REGION_NAME"
      description: "OS_REGION_NAME"
      type: "string"
    - variable: "PGHOARD_LOG_LEVEL"
      label: "PGHoard log level"
      description: "Log level PGHoard"
      type: "enum"
      options:
        - "DEBUG"
        - "INFO"
        - "WARNING"
        - "ERROR"
        - "CRITICAL"
      default: "INFO"
