version: '2'
services:
  nextcloud:
    image: nextcloud:13.0.7-apache
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
    volumes:
      - nextcloud_data:/var/www/html
    links:
      - postgres:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - 'nextcloud_pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_DB: postgres

volumes:
  nextcloud_data:
  nextcloud_pgdata:
