.catalog:
  name: "logging"
  version: "v6"
  description: "Camptocamp logging service. Add mandatory 'monitoring=true' label on exactly one host before installing."
  uuid: logging-6
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "TOKEN"
      label: "ELK Token"
      description: "Client token to be used when forwarding logs to camptocamp's ELK service. Leave empty if you haven't subscribed to this service."
      type: "string"
      default: ""
    - variable: "TARGET"
      label: "ELK entrypoint"
      description: "IP address of the ELK entrypoint. Same as above, leave empty by default."
      type: "string"
      default: ""
    - variable: "EXTRA"
      label: "Extra fields to add to structured logs"
      description: "JSON hash of key-values to add to each log. Example: {\"foo\":\"bar\"}"
      type: "string"
      default: "{}"

syslog:
  scale: 1
dispatcher-conf:
  scale: 1
cleanup:
  scale: 1
